CREATE TABLE IF NOT EXISTS todos (
  id PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NULL,
  todo TEXT NOT NULL,
)

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  password TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
)